//! Sandbox
//!
//! Actually runs each agent's evolved algorithm against real training/test
//! CSV data, instead of the deterministic timing/accuracy *proxies*
//! `evolution.rs`/`evaluator.rs` used before this existed (there was no
//! execution sandbox yet, and running untrusted model-generated code
//! without one would have been unsafe). This is that sandbox.
//!
//! ## Contract candidate code must follow
//! Candidate/original code is expected to be Python defining:
//! ```python
//! def run(train_path: str, test_path: str) -> float:
//!     """Trains on train_path, evaluates on test_path, returns accuracy in [0, 1]."""
//! ```
//! `evolution.rs`'s sample-generation prompt tells the model to follow
//! this contract, and `evaluator.rs` uses the same contract for both the
//! baseline and the evolved sample.
//!
//! ## What this sandbox actually protects against
//! This is a **process-level** sandbox: the candidate runs as a separate
//! OS process, in its own temp directory, killed automatically if it
//! exceeds a wall-clock timeout. That's enough to safely absorb the
//! failure modes evolutionary code search actually produces — infinite
//! loops, crashes, bad code — since what's being run here is generated by
//! your own local model for your own local task, not adversarial input
//! from the internet.
//!
//! It is **not** a security sandbox: the candidate process still has
//! whatever filesystem/network access your user account has. If you ever
//! plan to run candidates from an untrusted source (e.g. a remote model
//! you don't control, or user-submitted code), put this behind a real
//! OS-level sandbox first — a container, gVisor, a VM, or at minimum a
//! locked-down, unprivileged OS account with no network access.

use anyhow::{anyhow, Result};
use serde::Deserialize;
use std::process::Stdio;
use std::time::Duration;
use tokio::process::Command;
use tokio::time::timeout;

/// How long a candidate gets to run before it's killed and scored as a
/// (timeout) runtime error. Generous by default since classic ML
/// algorithms trained from scratch in Python can be slow; override via
/// the `SANDBOX_TIMEOUT_SECS` env var if needed.
pub fn default_time_limit() -> Duration {
    let secs = std::env::var("SANDBOX_TIMEOUT_SECS")
        .ok()
        .and_then(|s| s.parse::<u64>().ok())
        .unwrap_or(30);
    Duration::from_secs(secs)
}

/// Result of running one candidate against one training/test CSV pair.
#[derive(Debug, Clone)]
pub struct SandboxResult {
    /// 1 if the candidate failed to even compile (Python `SyntaxError`
    /// and friends), 0 otherwise. Capped at 1 because a single-file
    /// compile check reports only the first fatal syntax error.
    pub syntax_errors: u32,
    /// 1 if the candidate compiled but raised an exception (or timed
    /// out) while running, 0 otherwise.
    pub runtime_errors: u32,
    /// Test-set accuracy in [0, 1] the candidate reported. 0.0 if it
    /// never got that far.
    pub accuracy: f64,
    /// Wall-clock seconds the candidate took to run. 0.0 on a syntax
    /// error (never ran); equal to the timeout if it was killed for
    /// running too long.
    pub training_time_seconds: f64,
    /// Captured stderr/traceback text, for debugging a failed run. Empty
    /// on success.
    pub stderr: String,
}

#[derive(Deserialize)]
struct HarnessOutput {
    accuracy: f64,
    training_time_seconds: f64,
}

/// Wraps the candidate's `run(train_path, test_path)` function with a
/// small driver that times it, catches exceptions, and prints a single
/// JSON line with the result — the only thing the Rust side needs to
/// parse back out.
const HARNESS_TEMPLATE: &str = r#"
import sys, json, time, traceback

{candidate_code}

def _main():
    train_path, test_path = sys.argv[1], sys.argv[2]
    start = time.time()
    try:
        accuracy = run(train_path, test_path)
    except Exception:
        traceback.print_exc()
        sys.exit(1)
    elapsed = time.time() - start
    print(json.dumps({"accuracy": float(accuracy), "training_time_seconds": elapsed}))

if __name__ == "__main__":
    _main()
"#;

/// Runs `candidate_code` (must define `def run(train_path, test_path) -> float`,
/// see module docs) against the given training/test CSV text, inside a
/// fresh temp directory, killed if it exceeds `time_limit`.
pub async fn run(candidate_code: &str, training_csv: &str, test_csv: &str, time_limit: Duration) -> Result<SandboxResult> {
    let dir = tempfile::tempdir().map_err(|e| anyhow!("failed to create sandbox temp dir: {e}"))?;

    let train_path = dir.path().join("train.csv");
    let test_path = dir.path().join("test.csv");
    let script_path = dir.path().join("candidate.py");

    tokio::fs::write(&train_path, training_csv).await?;
    tokio::fs::write(&test_path, test_csv).await?;

    let script = HARNESS_TEMPLATE.replace("{candidate_code}", candidate_code);
    tokio::fs::write(&script_path, &script).await?;

    // ---- syntax check: compile without executing any of the candidate's code ----
    let compile = python_command()
        .arg("-m")
        .arg("py_compile")
        .arg(&script_path)
        .output()
        .await
        .map_err(|e| {
            anyhow!(
                "couldn't launch a Python interpreter ({e}). Install Python 3 and make sure \
                 it's on PATH (as `python3` on Linux/macOS, `python` on Windows), or set \
                 SANDBOX_PYTHON to the interpreter's full path."
            )
        })?;

    if !compile.status.success() {
        return Ok(SandboxResult {
            syntax_errors: 1,
            runtime_errors: 0,
            accuracy: 0.0,
            training_time_seconds: 0.0,
            stderr: String::from_utf8_lossy(&compile.stderr).to_string(),
        });
    }

    // ---- execute, with a hard timeout ----
    // `kill_on_drop(true)` is what makes the timeout actually stop the
    // process: if `timeout()` below cancels the future, the `Child` it
    // was holding gets dropped, and tokio kills the OS process for us.
    let child = python_command()
        .arg(&script_path)
        .arg(&train_path)
        .arg(&test_path)
        .current_dir(dir.path())
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .kill_on_drop(true)
        .spawn()?;

    let output = match timeout(time_limit, child.wait_with_output()).await {
        Ok(result) => result?,
        Err(_) => {
            return Ok(SandboxResult {
                syntax_errors: 0,
                runtime_errors: 1,
                accuracy: 0.0,
                training_time_seconds: time_limit.as_secs_f64(),
                stderr: format!("candidate timed out after {:.1}s", time_limit.as_secs_f64()),
            });
        }
    };

    if !output.status.success() {
        return Ok(SandboxResult {
            syntax_errors: 0,
            runtime_errors: 1,
            accuracy: 0.0,
            training_time_seconds: 0.0,
            stderr: String::from_utf8_lossy(&output.stderr).to_string(),
        });
    }

    let stdout_text = String::from_utf8_lossy(&output.stdout);
    let last_line = stdout_text.lines().last().unwrap_or_default();
    let parsed: HarnessOutput = serde_json::from_str(last_line).map_err(|e| {
        anyhow!("sandbox candidate exited successfully but produced unparseable output: {e}; stdout was: {stdout_text}")
    })?;

    Ok(SandboxResult {
        syntax_errors: 0,
        runtime_errors: 0,
        accuracy: parsed.accuracy.clamp(0.0, 1.0),
        training_time_seconds: parsed.training_time_seconds.max(1e-6),
        stderr: String::new(),
    })
}

fn python_command() -> Command {
    Command::new(python_bin())
}

fn python_bin() -> String {
    std::env::var("SANDBOX_PYTHON").unwrap_or_else(|_| default_python_name().to_string())
}

#[cfg(windows)]
fn default_python_name() -> &'static str {
    "python"
}

#[cfg(not(windows))]
fn default_python_name() -> &'static str {
    "python3"
}

#[cfg(test)]
mod tests {
    use super::*;

    const TRAIN_CSV: &str = "x1,x2,label\n1,1,0\n2,2,0\n8,8,1\n9,9,1";
    const TEST_CSV: &str = "x1,x2,label\n1,2,0\n8,7,1";

    #[tokio::test]
    async fn happy_path_reports_accuracy_and_time() {
        let code = "\
def run(train_path, test_path):
    return 0.875
";
        let result = run(code, TRAIN_CSV, TEST_CSV, Duration::from_secs(10)).await.unwrap();
        assert_eq!(result.syntax_errors, 0);
        assert_eq!(result.runtime_errors, 0);
        assert!((result.accuracy - 0.875).abs() < 1e-9);
        assert!(result.training_time_seconds > 0.0);
    }

    #[tokio::test]
    async fn syntax_error_is_caught_without_executing() {
        // Deliberately broken Python (unmatched paren, bad indent).
        let code = "def run(train_path, test_path:\n  return 1.0";
        let result = run(code, TRAIN_CSV, TEST_CSV, Duration::from_secs(10)).await.unwrap();
        assert_eq!(result.syntax_errors, 1);
        assert_eq!(result.runtime_errors, 0);
        assert_eq!(result.accuracy, 0.0);
        assert!(!result.stderr.is_empty());
    }

    #[tokio::test]
    async fn runtime_error_is_caught() {
        let code = "\
def run(train_path, test_path):
    return 1 / 0
";
        let result = run(code, TRAIN_CSV, TEST_CSV, Duration::from_secs(10)).await.unwrap();
        assert_eq!(result.syntax_errors, 0);
        assert_eq!(result.runtime_errors, 1);
        assert_eq!(result.accuracy, 0.0);
        assert!(result.stderr.contains("ZeroDivisionError"));
    }

    #[tokio::test]
    async fn infinite_loop_is_killed_by_timeout() {
        let code = "\
def run(train_path, test_path):
    while True:
        pass
";
        let start = std::time::Instant::now();
        let result = run(code, TRAIN_CSV, TEST_CSV, Duration::from_millis(500)).await.unwrap();
        let elapsed = start.elapsed();

        assert_eq!(result.runtime_errors, 1);
        assert!(result.stderr.contains("timed out"));
        // Should not have waited anywhere close to how long `while True` would run.
        assert!(elapsed < Duration::from_secs(5), "elapsed = {:?}", elapsed);
    }

    #[tokio::test]
    async fn candidate_can_actually_read_the_csv_paths() {
        // Confirms the harness really passes usable file paths through,
        // not just placeholders.
        let code = "\
import csv

def run(train_path, test_path):
    with open(train_path) as f:
        rows = list(csv.reader(f))
    with open(test_path) as f:
        test_rows = list(csv.reader(f))
    # header + 4 data rows in TRAIN_CSV, header + 2 in TEST_CSV
    assert len(rows) == 5, len(rows)
    assert len(test_rows) == 3, len(test_rows)
    return 1.0
";
        let result = run(code, TRAIN_CSV, TEST_CSV, Duration::from_secs(10)).await.unwrap();
        assert_eq!(result.runtime_errors, 0, "stderr: {}", result.stderr);
        assert_eq!(result.accuracy, 1.0);
    }
}
